/* A textless master: a demo with its captions and its music taken out.
 *
 *   node demos/_src/textless.mjs 08-product-tour 13-cutdowns/master
 *
 * An editor cuts shorter versions from a master that carries picture and
 * effects only: the captions of the long version would say the wrong thing in
 * a short one, and music cut at every splice jumps off its beat (#27). So the
 * cutdowns are cut from this, and each lays its own words and one continuous
 * music bed on top. The master is generated from the source demo so the two
 * can never drift apart.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const DEMOS = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const [from, to] = process.argv.slice(2);
if (!from || !to) { console.error("usage: textless.mjs <source demo> <output dir>"); process.exit(2); }
const SRC = join(DEMOS, from), OUT = join(DEMOS, to);

let html = readFileSync(join(SRC, "index.html"), "utf8");
const cut = (what, re) => {
  const n = (html.match(re) || []).length;
  if (n === 0) throw new Error(`${from}: found no ${what} to remove — the source changed, update textless.mjs`);
  html = html.replace(re, "");
  return n;
};
const music = cut("music track", /\s*<audio id="bgm"[^>]*><\/audio>/g);
const gain = cut("music automation", /\s*tl\.(?:fromTo|to)\("#bgm"[\s\S]*?\);/g);
// the captions stay in the DOM so the timeline is untouched; they just never paint
html = html.replace("</style>", "      .cap { display:none !important; }\n    </style>");
html = html.replace("<!doctype html>\n<!--",
  `<!doctype html>\n<!--\n  GENERATED by demos/_src/textless.mjs from ${from} — picture and effects\n  only, the master its cutdowns are cut from. Edit ${from}, never this file.\n`);

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "index.html"), html, "utf8");
writeFileSync(join(OUT, "meta.json"), JSON.stringify({ id: "main", name: to.replace(/\//g, "-") }) + "\n");
writeFileSync(join(OUT, "package.json"), JSON.stringify({
  name: "main", private: true, type: "module",
  scripts: { render: "npx --yes hyperframes@0.8.48 render" },
}, null, 2) + "\n");
const link = join(OUT, "assets");
if (!existsSync(link)) {
  const target = join(DEMOS, "_assets");
  const r = process.platform === "win32"
    ? spawnSync("cmd", ["/c", "mklink", "/J", link, target])
    : spawnSync("ln", ["-s", relative(OUT, target), link]);
  if (r.status !== 0) throw new Error(`could not link ${link}`);
}
console.log(`${from} → ${to}: ${music} music track and ${gain} gain tween(s) removed, captions hidden`);
